# Generated by Django 2.2.6 on 2019-10-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BdgCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='BdgItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('expected_amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Category Item',
            },
        ),
        migrations.CreateModel(
            name='BdgTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Transaction type',
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.BdgItems')),
            ],
            options={
                'verbose_name': 'Transaction logging',
            },
        ),
        migrations.AddField(
            model_name='bdgitems',
            name='bdgType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.BdgTypes'),
        ),
        migrations.AddField(
            model_name='bdgitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.BdgCategories'),
        ),
    ]
