# Generated by Django 2.2.6 on 2019-10-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='entries',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'managed': False},
        ),
    ]
